apiVersion: v2
appVersion: "0.0.1"
version: 0.1.13
name: admission-controller
description: Lacework admission controller using Lacework proxy scanner
type: application
keywords:
- admission-controller
- runtime-security
- lacework
maintainers:
  - name: chitrapkumar
    email: chitra.kumar@lacework.net
dependencies:
  - name: proxy-scanner
    version: 0.9.0
    condition: proxy-scanner.enabled
    repository: https://lacework.github.io/helm-charts