{{- if .Values.windowsAgent.enable -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "lacework-windows-agent.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: monitoring
    app: {{ include "lacework-windows-agent.name" . }}
    {{- with .Values.windowsAgent.agentConfig.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.windowsAgent.agentConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      name: {{ include "lacework-windows-agent.name" . }}
  template:
    metadata:
      {{- with .Values.windowsAgent.agentConfig.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        name: {{ include "lacework-windows-agent.name" . }}
        {{- with .Values.windowsAgent.agentConfig.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      affinity:
{{ toYaml .Values.windowsAgent.daemonset.affinity | indent 8 }}
{{- if .Values.windowsAgent.priorityClassName }}
      priorityClassName: {{ .Values.windowsAgent.priorityClassName | quote }}
{{- end }}
{{- if .Values.windowsAgent.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.windowsAgent.image.imagePullSecrets | indent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 40
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\SYSTEM"
      containers:
      - name: lwdatacollector
        image: {{ template "lacework-windows-agent.image" . }}
        imagePullPolicy: {{ .Values.windowsAgent.image.pullPolicy }}
        env:
{{- if .Values.windowsAgent.agentConfig.stdoutLogging }}
          - name: LaceworkLogStdout
            value: "yes"
{{- end }}
          - name: LaceworkAccessToken
            valueFrom:
              secretKeyRef:
{{- if kindIs "string" .Values.windowsAgent.agentConfig.accessToken }}
                name: {{ include "lacework-windows-agent.name" . }}-access-token
                key: agent-access-token
{{- else }}
                name: {{ required "Secret name required for existing secret" .Values.windowsAgent.agentConfig.accessToken.existingSecret.name }}
                key: {{ required "Key name required for existing secret" .Values.windowsAgent.agentConfig.accessToken.existingSecret.key }}
{{- end}}
        resources:
{{ toYaml .Values.windowsAgent.resources | indent 12 }}
        volumeMounts:
          - name: cfgmap
            mountPath: /var/lacework/config
          - name: podinfo
            mountPath: /var/lacework/podinfo
      volumes:
        - name: cfgmap
          configMap:
            name: lacework-windows-config
            items:
            - key: config.json
              path: config.json
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
              - path: "name"
                fieldRef:
                  fieldPath: metadata.name
              - path: "poduid"
                fieldRef:
                  fieldPath: metadata.uid
              - path: "namespace"
                fieldRef:
                  fieldPath: metadata.namespace
      {{- if kindIs "string" .Values.windowsAgent.agentConfig.serviceAccountName }}
      serviceAccountName: {{ .Values.windowsAgent.agentConfig.serviceAccountName | quote }}
      {{- end}}
  updateStrategy:
{{ toYaml .Values.windowsAgent.daemonset.updateStrategy | indent 4 }}

{{- end }}
