{{- if kindIs "string" .Values.laceworkConfig.accessToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lacework-agent.name" . }}-access-token
  labels:
    tier: monitoring
    app: {{ include "lacework-agent.name" . }}
    {{- with .Values.laceworkConfig.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.laceworkConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
type: Opaque
data:
  agent-access-token: {{ required "A valid AccessToken is required! Specify your Lacework agent token in values.yaml" .Values.laceworkConfig.accessToken | b64enc }}
{{- end -}}
