{{- if (.Values.clusterAgent).enable -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lacework-agent.name" . }}-cluster
  namespace: {{ .Release.Namespace }}
  labels:
    tier: monitoring
    app: {{ include "lacework-agent.name" . }}-cluster
    {{- with (.Values.laceworkConfig).labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (.Values.laceworkConfig).annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      name: {{ include "lacework-agent.name" . }}-cluster
  template:
    metadata:
      {{- with (.Values.laceworkConfig).annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "lacework-agent.name" . }}
        app.kubernetes.io/instance: {{ include "lacework-agent.name" . }}
        name: {{ include "lacework-agent.name" . }}-cluster
    spec:
      serviceAccountName: cluster-{{ include "lacework-agent.name" . }}-sa
      affinity:
{{ toYaml (.Values.deployment).affinity | indent 8 }}
      tolerations:
{{ toYaml (.Values.deployment).tolerations | indent 8 }}
{{- if or (.Values.deployment).priorityClassCreate .Values.priorityClassName }}
      priorityClassName: {{ or (.Values.deployment).priorityClassName .Values.priorityClassName  | default (include "lacework-agent.fullname" . ) }}
{{- end }}
{{- if ((.Values.clusterAgent).image).imagePullSecrets }}
      imagePullSecrets:
{{ toYaml ((.Values.clusterAgent).image).imagePullSecrets | indent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 20
{{- if (.Values.clusterAgent).hostNetworkAccess }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
{{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 5001
      volumes:
      - name: cfgmap
        configMap:
          defaultMode: 0640
          name: lacework-cluster-config
          items:
          - key: config.yaml
            path: config.yaml
      containers:
      - name: {{ include "lacework-agent.name" . }}-cluster
        image: {{ template "lacework-cluster-agent.image" . }}
        imagePullPolicy: {{ ((.Values.clusterAgent).image).pullPolicy }}
        env:
          - name: LaceworkAccessToken
            valueFrom:
              secretKeyRef:
{{- if kindIs "string" (.Values.laceworkConfig).accessToken }}
                name: {{ include "lacework-agent.name" . }}-access-token
                key: agent-access-token
{{- else }}
                name: {{ required "Secret name required for existing secret" (((.Values.laceworkConfig).accessToken).existingSecret).name }}
                key: {{ required "Key name required for existing secret" (((.Values.laceworkConfig).accessToken).existingSecret).key }}
{{- end}}
        resources:
          requests:
{{ toYaml (.Values.resources).requests | indent 12 }}
          limits:
{{ toYaml (.Values.resources).limits | indent 12 }}
        volumeMounts:
          - name: cfgmap
            mountPath: /config
{{- end -}}
