{{- if (and (.Values.clusterAgent).enable (.Values.clusterAgent).createRole) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: cluster-{{ include "lacework-agent.name" . }}-role
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
{{- end -}}
