apiVersion: apps/v1

kind: DaemonSet
metadata:
  name: {{ include "lacework-agent.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: monitoring
    app: {{ include "lacework-agent.name" . }}
    {{- with .Values.laceworkConfig.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.laceworkConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      name: {{ include "lacework-agent.name" . }}
  template:
    metadata:
      {{- with .Values.laceworkConfig.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        name: {{ include "lacework-agent.name" . }}
    spec:
      affinity:
{{ toYaml .Values.daemonset.affinity | indent 8 }}
      tolerations: 
{{ toYaml .Values.tolerations | indent 8 }}
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
{{- end }}
{{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 20
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: lacework
        image: {{ template "lacework-agent.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
{{- if .Values.laceworkConfig.stdoutLogging }}
          - name: LaceworkLogStdout
            value: "yes"
{{- end }}
          - name: LaceworkAccessToken
            valueFrom:
              secretKeyRef:
{{- if kindIs "string" .Values.laceworkConfig.accessToken }}
                name: {{ include "lacework-agent.name" . }}-access-token
                key: agent-access-token
{{- else }}
                name: {{ required "Secret name required for existing secret" .Values.laceworkConfig.accessToken.existingSecret.name }}
                key: {{ required "Key name required for existing secret" .Values.laceworkConfig.accessToken.existingSecret.key }}
{{- end}}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: true
        volumeMounts:
          - name: cfgmap
            mountPath: /var/lib/lacework/config
          - name: dev
            mountPath: /dev
          - name: sys
            mountPath: /sys
          - name: log
            mountPath: /var/log
          - name: passwd
            mountPath: /etc/passwd
            readOnly: true
          - name: group
            mountPath: /etc/group
            readOnly: true
          - name: hostlacework
            mountPath: /var/lib/lacework/collector
          - name: hostlaceworkcontroller
            mountPath: /var/lib/lacework/controller
          - name: hostroot
            mountPath: /laceworkfim
            readOnly: true
          - name: podinfo
            mountPath: /etc/podinfo
{{- if kindIs "string" .Values.laceworkConfig.serviceAccountName }}
      serviceAccountName: {{ .Values.laceworkConfig.serviceAccountName | quote }}
{{- end}}
      volumes:
        - name: dev
          hostPath:
              path: /dev
        - name: sys
          hostPath:
              path: /sys
        - name: log
          hostPath:
              path: /var/log
        - name: passwd
          hostPath:
              path: /etc/passwd
        - name: group
          hostPath:
              path: /etc/group
        - name: hostroot
          hostPath:
              path: /
        - name: hostlacework
          hostPath:
              path: /var/lib/lacework/collector
        - name: hostlaceworkcontroller
          hostPath:
              path: /var/lib/lacework/controller
        - name: cfgmap
          configMap:
            defaultMode: 0640
            name: lacework-config
            items:
            - key: config.json
              path: config.json
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
              - path: "name"
                fieldRef:
                  fieldPath: metadata.name
              - path: "poduid"
                fieldRef:
                  fieldPath: metadata.uid
              - path: "namespace"
                fieldRef:
                  fieldPath: metadata.namespace
  updateStrategy:
{{ toYaml .Values.daemonset.updateStrategy | indent 4 }}
