apiVersion: apps/v1

kind: DaemonSet
metadata:
  name: {{ include "lacework-agent.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: monitoring
    app: {{ include "lacework-agent.name" . }}
spec:
  selector:
    matchLabels:
      name: {{ include "lacework-agent.name" . }}
  template:
    metadata:
      labels:
        name: {{ include "lacework-agent.name" . }}
    spec:
      tolerations: 
{{ toYaml .Values.tolerations | indent 8 }}
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
{{- end }}
{{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 20
      hostPID: true
      hostNetwork: true
      containers:
      - name: lacework
        image: {{ template "lacework-agent.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: LaceworkLogStdout
            value: "yes"
          - name: LaceworkAccessToken
            valueFrom:
              secretKeyRef:
                name: {{ include "lacework-agent.name" . }}-access-token
                key: agent-access-token
        resources:
{{ toYaml .Values.resources | indent 12 }}
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: true
        volumeMounts:
          - name: cfgmap
            mountPath: /var/lib/lacework/config
          - name: dev
            mountPath: /dev
          - name: run-sock
            mountPath: /var/run/docker.sock
          - name: run-pid
            mountPath: /var/run/docker.pid
          - name: sys
            mountPath: /sys
          - name: log
            mountPath: /var/log
          - name: passwd
            mountPath: /etc/passwd
            readOnly: true
          - name: group
            mountPath: /etc/group
            readOnly: true
          - name: hostlacework
            mountPath: /var/lib/lacework/collector
          - name: hostroot
            mountPath: /laceworkfim
            readOnly: true
          - name: podinfo
            mountPath: /etc/podinfo
      volumes:
        - name: dev
          hostPath:
              path: /dev
        - name: run-sock
          hostPath:
              path: /var/run/docker.sock
        - name: run-pid
          hostPath:
              path: /var/run/docker.pid
        - name: sys
          hostPath:
              path: /sys
        - name: log
          hostPath:
              path: /var/log
        - name: passwd
          hostPath:
              path: /etc/passwd
        - name: group
          hostPath:
              path: /etc/group
        - name: hostroot
          hostPath:
              path: /
        - name: hostlacework
          hostPath:
              path: /var/lib/lacework/collector
        - name: cfgmap
          configMap:
            name: lacework-config
            items:
            - key: config.json
              path: config.json
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
              - path: "name"
                fieldRef:
                  fieldPath: metadata.name
              - path: "poduid"
                fieldRef:
                  fieldPath: metadata.uid
              - path: "namespace"
                fieldRef:
                  fieldPath: metadata.namespace
  updateStrategy:
{{ toYaml .Values.daemonset.updateStrategy | indent 4 }}
