{{- if (and (.Values.clusterAgent).enable (.Values.clusterAgent).createServiceAccount) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-{{ include "lacework-agent.name" . }}-sa
  namespace: {{ .Release.Namespace }}
{{- end -}}
