{{- if (and (not .Values.config.registry_secret_name) .Values.config.registries) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scanner.name" . }}-registry-secrets
  labels:
    tier: monitoring
    app: {{ include "scanner.name" . }}
type: Opaque
data:
  registries: {{ quote .Values.config.registries | b64enc }}
{{- end -}}