---
kind: Service
apiVersion: v1
metadata:
  labels:
    role: {{ include "scanner.fullname" . }}
  name: {{ include "scanner.fullname" . }}
spec:
  selector:
    app: {{ include "scanner.fullname" . }}  
  ports:
    - port: 8080
      targetPort: 8080
