apiVersion: v1
appVersion: "1.0"
description: Lacework Agent
home: https://www.lacework.com
icon: https://www.lacework.com/wp-content/uploads/2019/07/Lacework_Logo_color_2019.svg
keywords:
- monitoring
- security
- run-time
- metric
- troubleshooting
maintainers:
- email: info@lacework.net
  name: lacework-support
name: lacework-agent
version: 5.0.0
