apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certs.name }}
data:
{{- if not .Values.scanner.skipVerify }}
  ca.crt: {{ .Values.scanner.caCert }} # root CA for scanner
{{- end }}
  admission.crt: {{ .Values.certs.serverCertificate }}  # place server cert
  admission.key: {{ .Values.certs.serverKey }}  # place server key