apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "admission.fullname" . }}
rules:
  - apiGroups: ["validate.lacework.net"]
    resources: [{{ include "admission.fullname" . }}]
    verbs: [ "get", "list", "watch", "create" ]